//! Generates a Lua API reference/stub file describing every global a
//! Basic2D game script can use. The output is safe to load (it only
//! defines the `Basic2D_API` index table plus editor annotations), so Lua
//! tooling (LuaLS / EmmyLua) can use it for autocompletion.

const std = @import("std");
const win32 = @import("win32.zig");

pub fn writeLuaApiFile(allocator: std.mem.Allocator, path: []const u8) !void {
    const path_z = try allocator.dupeZ(u8, path);
    defer allocator.free(path_z);

    const GENERIC_WRITE: u32 = 0x40000000;
    const CREATE_ALWAYS: u32 = 2;
    const fh = win32.CreateFileA(path_z, GENERIC_WRITE, 0, null, CREATE_ALWAYS, 0x80, null) orelse
        return error.FileWriteFailed;
    defer _ = win32.CloseHandle(fh);
    var written: u32 = 0;
    _ = win32.WriteFile(fh, api_text.ptr, @intCast(api_text.len), &written, null);
    std.debug.print("Lua API written to: {s}\n", .{path});
}

const api_text =
    \\-- Basic2D Lua API reference — generated by the engine.
    \\-- Regenerate: zig build run -- --generate-api <path>
    \\-- Or from a game script: Engine.GenerateApi("<path>")
    \\--
    \\-- Loading this file is safe: it only defines the Basic2D_API index
    \\-- table and editor annotations (LuaLS / EmmyLua), nothing else.
    \\-- Every global listed here exists inside a Basic2D game script.
    \\
    \\---@meta basic2d
    \\
    \\-- =====================================================================
    \\-- VALUE TYPES
    \\-- =====================================================================
    \\
    \\---@class Vector2 @A 2D vector, like Unity's Vector2.
    \\---@field x number
    \\---@field y number
    \\-- Construct:   Vector2(x, y)
    \\-- Statics:     Vector2.zero .one .up .down .left .right
    \\-- Methods:     Vector2.Distance(a, b), Vector2.Lerp(a, b, t)
    \\-- Instance:    v.magnitude, v.normalized
    \\-- Operators:   + - * (scalar or Vector2), unary -, ==
    \\
    \\---@class Color @An RGBA color, like Unity's Color.
    \\---@field r number
    \\---@field g number
    \\---@field b number
    \\---@field a number
    \\-- Construct:   Color(r, g, b, a)
    \\-- Statics:     Color.white .black .red .green .blue .yellow .cyan
    \\--              Color.magenta .gray .clear
    \\
    \\-- =====================================================================
    \\-- WORLD / ECS
    \\-- =====================================================================
    \\
    \\---@class GameObject @An ECS entity handle, like Unity's GameObject.
    \\---@field name string @Get/set the object name.
    \\---@field tag string|nil @Get/set a Unity-style tag (nil clears).
    \\---@field active boolean @Also readable as activeSelf.
    \\---@field transform Transform @The (implicit) Transform component.
    \\---@field sprite SpriteRenderer|nil
    \\---@field boxCollider Collider2D|nil
    \\---@field circleCollider Collider2D|nil
    \\---@field textMesh TextMesh|nil
    \\
    \\-- World.Spawn(name) -> GameObject
    \\-- World.Add(go, "Component", ...) -> component
    \\--     components: "Transform" | "SpriteRenderer" | "TextMesh" |
    \\--     "BoxCollider2D"(w, h) | "CircleCollider2D"(r) |
    \\--     "UIImage" | "UIText" | "UIButton" | "Script"(table)
    \\-- World.Get(go, "Component") -> component|nil
    \\-- World.Remove(go, "Component")
    \\-- World.Has(go, "Component") -> boolean
    \\-- World.Destroy(go)          (also global Destroy(go))
    \\-- World.EntityCount() -> integer
    \\-- for entity, component in World.Query("SpriteRenderer") do ... end
    \\-- World.AddSystem(function(dt) ... end)   -- runs every frame
    \\
    \\---@class Transform @Position/rotation/scale, like Unity's Transform.
    \\---@field position Vector2
    \\---@field rotation number @Radians (Unity uses degrees for eulerAngles).
    \\---@field scale Vector2
    \\---@field gameObject GameObject
    \\
    \\---@class SpriteRenderer @Draws a shape/texture, like SpriteRenderer.
    \\---@field color Color
    \\---@field size Vector2
    \\---@field shape "Quad"|"Circle"
    \\---@field visible boolean
    \\---@field sprite Sprite|nil @Assigning auto-sizes to the image.
    \\---@field flipX boolean
    \\---@field flipY boolean
    \\---@field sortingOrder integer @Higher draws on top.
    \\---@field drawMode "Simple"|"Sliced" @Sliced = 9-slice.
    \\---@field gameObject GameObject
    \\
    \\---@class Sprite @A texture asset, like Unity's Sprite.
    \\---@field width number
    \\---@field height number
    \\---@field borderLeft number
    \\---@field borderBottom number
    \\---@field borderRight number
    \\---@field borderTop number
    \\-- Method: sprite:SetBorder(l, b, r, t)
    \\
    \\---@class TextMesh @World-space text, like Unity's TextMesh.
    \\---@field text string
    \\---@field fontSize number
    \\---@field color Color
    \\---@field sortingOrder integer
    \\---@field gameObject GameObject
    \\
    \\---@class Collider2D @Box or circle collision shape.
    \\---@field size Vector2 @BoxCollider2D only.
    \\---@field radius number @CircleCollider2D only.
    \\---@field gameObject GameObject
    \\
    \\-- =====================================================================
    \\-- SCREEN-SPACE UI (anchored, drawn on top, camera-independent)
    \\-- =====================================================================
    \\
    \\---@class UIImage @A solid/sprite rectangle, like Unity's UI Image.
    \\---@field anchor string @See UI_ANCHORS below.
    \\---@field offset Vector2 @Pixels from the anchor point.
    \\---@field size Vector2
    \\---@field color Color
    \\---@field sprite Sprite|nil
    \\---@field drawMode "Simple"|"Sliced"
    \\---@field visible boolean
    \\---@field sortingOrder integer
    \\---@field gameObject GameObject
    \\
    \\---@class UIText @A screen-space label, like Unity's UI Text.
    \\---@field text string
    \\---@field fontSize number
    \\---@field color Color
    \\---@field anchor string
    \\---@field offset Vector2
    \\---@field visible boolean
    \\---@field sortingOrder integer
    \\---@field gameObject GameObject
    \\
    \\---@class UIButton @A clickable button with hover/pressed tints.
    \\---@field label string
    \\---@field fontSize number
    \\---@field size Vector2
    \\---@field anchor string
    \\---@field offset Vector2
    \\---@field normalColor Color
    \\---@field hoverColor Color
    \\---@field pressedColor Color
    \\---@field labelColor Color
    \\---@field visible boolean
    \\---@field sortingOrder integer
    \\---@field hover boolean @Read-only state.
    \\---@field pressed boolean @Read-only state.
    \\---@field onClick fun() @Callback, fires on release inside the rect.
    \\---@field gameObject GameObject
    \\
    \\-- UI_ANCHORS: "TopLeft" "TopCenter" "TopRight" "MiddleLeft" "Center"
    \\--             "MiddleRight" "BottomLeft" "BottomCenter" "BottomRight"
    \\
    \\-- =====================================================================
    \\-- GLOBAL TABLES AND FUNCTIONS
    \\-- =====================================================================
    \\
    \\-- Engine.CreateGameObject(name) -> GameObject   (GameObject facade)
    \\-- Engine.Find(name) -> GameObject|nil
    \\-- Engine.FindWithTag(tag) -> GameObject|nil
    \\-- Engine.LoadSprite(path) -> Sprite            (BMP or PNG)
    \\-- Engine.OnUpdate(function(dt) ... end)        (single callback)
    \\-- Engine.SetBackground(r, g, b[, a])           (or pass a Color)
    \\-- Engine.SetCameraPosition(Vector2)
    \\-- Engine.SetZoom(number)                       (clamped 0.1..10)
    \\-- Engine.ScreenSize() -> Vector2
    \\-- Engine.CaptureScreenshot(path) -> next frame as BMP
    \\-- Engine.GenerateApi(path) -> writes this reference file
    \\-- Engine.Quit()
    \\-- Engine.screenWidth / Engine.screenHeight     (numbers, read-only)
    \\-- Engine.zoom / Engine.background(Color) / Engine.cameraPosition(Vector2)
    \\
    \\-- GameObject.Find(name) -> GameObject|nil
    \\-- GameObject.FindWithTag(tag) -> GameObject|nil
    \\-- Destroy(go)                                  (global, idempotent)
    \\
    \\-- Input.GetKey("LeftArrow") / Input.GetKeyDown("LeftArrow") -> boolean
    \\-- Input.GetAxisRaw("Horizontal"|"Vertical") -> number in [-1, 1]
    \\-- Input.GetMouseButton(n) / Input.GetMouseButtonDown(n) -> boolean
    \\-- Input.mousePosition (Vector2, bottom-left origin)
    \\-- Input.mouseScrollDelta (Vector2, mouse wheel)
    \\
    \\-- Debug.Log(...) / Debug.LogWarning(...) / Debug.LogError(...)
    \\
    \\-- Mathf.Clamp / Mathf.Lerp / Mathf.Abs / Mathf.Sin / Mathf.Cos
    \\-- Mathf.Sqrt / Mathf.Pow / Mathf.Min / Mathf.Max / Mathf.Floor
    \\-- Mathf.Ceil / Mathf.RandomRange(lo, hi) / Mathf.PI
    \\
    \\-- Physics2D.OverlapCircle(center, radius[, ignore]) -> GameObject|nil
    \\-- Physics2D.OverlapBox(center, half[, ignore]) -> GameObject|nil
    \\-- (queries only — no simulation yet)
    \\
    \\-- Time.deltaTime / Time.time / Time.frameCount   (numbers)
    \\-- WaitForSeconds(n)  — for coroutines: coroutine.yield(WaitForSeconds(1))
    \\
    \\-- =====================================================================
    \\-- RUNTIME INDEX (safe to load: defines Basic2D_API and returns it)
    \\-- =====================================================================
    \\
    \\Basic2D_API = {
    \\  engine = "Basic2D",
    \\  globals = {
    \\    "Engine", "Input", "Debug", "Mathf", "Physics2D", "Time",
    \\    "Vector2", "Color", "World", "GameObject",
    \\    "Destroy", "WaitForSeconds",
    \\  },
    \\  components = {
    \\    "Transform", "SpriteRenderer", "TextMesh",
    \\    "BoxCollider2D", "CircleCollider2D", "Script",
    \\    "UIImage", "UIText", "UIButton",
    \\  },
    \\  ui_anchors = {
    \\    "TopLeft", "TopCenter", "TopRight",
    \\    "MiddleLeft", "Center", "MiddleRight",
    \\    "BottomLeft", "BottomCenter", "BottomRight",
    \\  },
    \\}
    \\
    \\return Basic2D_API
    \\
;
